### ISSUE TITLE
Getting groups to work with references

### ISSUE THREAD

**Issue by Kristopher38** [Tyulis/rawutil#3]
Consider this minimal example:
```Python
>>> rawutil.pack("B /0[n]", 2, [["foo"], ["bar"]])
b'\x02foo\x00bar\x00'
>>> rawutil.unpack("B /0[n]", b'\x02foo\x00bar\x00')
[2, [[b'foo'], [b'bar']]]
```
This works fine, but what if I wanted `foo` and `bar` not inside their own lists, like so:
```Python
[2, [b'foo', b'bar']]
```
Obvious idea that comes to mind is to use a group instead of an iterator, because group doesn't enclose each of its occurence in a list:
```Python
>>> rawutil.unpack("B (/0n)", b'\x02foo\x00bar\x00')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Krzychu\Desktop\rawutilbugs\rawutil.py", line 619, in unpack
    unpacked, ptr = _unpack(stct, data, None, byteorder, refdata)
  File "C:\Users\Krzychu\Desktop\rawutilbugs\rawutil.py", line 56, in __new__
    return ins.main(*args, **kwargs)
  File "C:\Users\Krzychu\Desktop\rawutilbugs\rawutil.py", line 320, in main
    return self.unpack(stct)
  File "C:\Users\Krzychu\Desktop\rawutilbugs\rawutil.py", line 334, in unpack
    final.append(self.unpack(el.stct)[0])
  File "C:\Users\Krzychu\Desktop\rawutilbugs\rawutil.py", line 329, in unpack
    count = final[count.index]
IndexError: list index out of range
```
This doesn't seem to work, but manually specifying repeating amount does work:
```Python
>>> rawutil.unpack("B (2n)", b'\x02foo\x00bar\x00')
[2, [b'foo', b'bar']]
```
This also works, but it's not what I want (`foo` and `bar` in their own list, separated from their count):
```Python
>>> rawutil.unpack("(B /0n)", b'\x02foo\x00bar\x00')
[[2, b'foo', b'bar']]
>>> rawutil.unpack("B /0n", b'\x02foo\x00bar\x00')
[2, b'foo', b'bar']
```
So it seems like references are local to a group. Was this a conscious design decision or it just happens to work that way? I'd like to get `[2, [b'foo', b'bar']]` without any further pre or postprocessing of the items, but it's not possible in the current implementation.

**Comment by Tyulis** [comment]
To start with your second question, references are local to a group by design, because otherwise situations like this (basically, any structure where you need a reference inside a group or to reference a value between iterators) would be very complicated : 
```python
>>> rawutil.unpack("B /0[2I] B /2[2I]", […])
>>> rawutil.unpack("B /0[B /0s]", […])
```
This was done before relative references, so it was a problem at that time — but anyway, it would not be practical, and the implementation would be quite complicated.
But it was indeed not told in the doc, I clarified this point in the readme.


And for your problem, it would indeed be cleaner that way, and it’s indeed not possible in the current implementation.
So I just added that feature, you can now use `B /0(n)` (or whatever number or reference you need), the content of the instances of the group will then be extracted in the same list : 

```python
>>> rawutil.unpack("B /0(n)", b"\x02foo\x00bar\x00")
[2, [b’foo’, b’bar’]]
>>> rawutil.unpack("B /0(2B)", b"\x03\x00\x01\x02\x03\x04\x05")
[3, [0, 1, 2, 3, 4, 5]]
```

Thank you very much for your input !

**Comment by Kristopher38** [comment]
Thank you so much for such a quick response! Rawutil has been a very useful tool and grouping elements inside one large list was one of my use cases, so I'm overjoyed to see it implemented so quickly. I'll be sure to test this to check if I can find any edge cases.
